=== demis131194/masterjava/src/main/resources/payload_hw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">

        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="1">
                            <xs:element ref="Groups"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

        </xs:complexType>

<!--        <xs:complexType>-->
<!--            <xs:all>-->
<!--                <xs:element name="Cities">-->
<!--                    <xs:complexType>-->
<!--                        <xs:sequence minOccurs="1" maxOccurs="unbounded">-->
<!--                            <xs:element ref="City"/>-->
<!--                        </xs:sequence>-->
<!--                    </xs:complexType>-->
<!--                </xs:element>-->
<!--                <xs:element ref="Users"/>-->
<!--            </xs:all>-->
<!--        </xs:complexType>-->

    </xs:element>

    <xs:element name="Groups">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="Group"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element ref="Users"/>
            </xs:sequence>
            <xs:attribute type="groupStatus" name="status" use="required"/>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:string" name="email" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="groupStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== demis131194/masterjava/src/test/resources/payload_hw.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload_hw.xsd">

    <Projects>
        <Groups>
            <Group status="FINISHED" name="topjava">
                <Users>
                    <User flag="active" city="kiv" email="gmail@gmail.com">
                        <fullName>Full Name</fullName>
                    </User>
                    <User flag="superuser" city="spb" email="admin@javaops.ru">
                        <fullName>Admin</fullName>
                    </User>
                    <User flag="deleted" city="spb" email="mail@yandex.ru">
                        <fullName>Deleted</fullName>
                    </User>
                </Users>
            </Group>
            <Group status="CURRENT" name="masterjava">
                <Users>
                    <User flag="superuser" city="spb" email="admin@javaops.ru">
                        <fullName>Admin</fullName>
                    </User>
                    <User flag="active" city="mnsk" email="demis@gmail.com">
                        <fullName>Denis Katsuk</fullName>
                    </User>
                    <User flag="active" city="spb" email="mail@yandex.ru">
                        <fullName>Petya</fullName>
                    </User>
                </Users>
            </Group>
            <Group status="REGISTERING" name="masterjava">
                <Users>
                    <User flag="superuser" city="spb" email="admin@javaops.ru">
                        <fullName>Admin</fullName>
                    </User>
                    <User flag="active" city="mglv" email="demis@gmail.com">
                        <fullName>Vasya</fullName>
                    </User>
                </Users>
            </Group>
        </Groups>
    </Projects>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
        <City id="mglv">Могилев</City>
    </Cities>
</Payload>
